# Site settings
title: Twenty
subtitle: by HTML5 UP
description: >- # this means to ignore newlines until "baseurl:"
  A responsive site template designed by HTML5 Up<br>
  and released under the Creative Commons.

# Contact information
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555
email: youremailaddress@gmail.com

# Social settings
500px_url: https://github.com/apehex
facebook_url: https://github.com/apehex
github_url: https://github.com/apehex
gitlab_url: https://github.com/apehex
instagram_url: https://github.com/apehex
linkedin_url: https://github.com/apehex
pinterest_url: https://github.com/apehex
slack_url: https://github.com/apehex
twitter_url: https://github.com/apehex

# Optional elements
logo_url: /assets/images/logo.svg
legal_terms_url: /legal-terms
privacy_policy_url: /privacy-policy

# Collections
collections:
  articles:
    output: false

# Build settings
permalink: pretty
markdown: kramdown
sass:
  style: compressed

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: apehex

# Exclude from processing
